swagger: "2.0"
info:
  title: "Books"
  version: "1.1.0"
paths:
  /books/{id}:
    get:
      summary: "Return book's details"
      description: "Returns book's details for given id"
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          description: "Unique book id"
          type: integer
          required: true
      responses:
        200:
          description: "Successfully returned a book"
          schema:
            $ref: "#/definitions/Book"
      deprecated: false
  /books:
    get:
      summary: "Returns a list of all books"
      description: "Returns a list of all books and the total number of books"
      responses:
        200:
          description: "Successfully returned a list of all books"
          schema:
            type: object
            required:
              - total_count
              - items
            properties:
              total_count:
                description: "Total number of books in the list"
                type: integer
              items:
                description: "list of books"
                type: array
                items:
                  $ref: "#/definitions/Book"
    post:
      summary: "Adds a new book"
      description: "Add a new book to the list"
      parameters:
        - name: Books
          in: body
          schema:
            type: object
            required:
              - title
              - author
            properties:
              title:
                description: "Name of the book"
                type: string
              author:
                description: "Author of the book"
                type: string
              synopsis:
                description: "Brief summary of the book"
                type: string
      responses:
        201:
          description: "Successfully added book"
          schema:
            $ref: "#/definitions/Book"
definitions:
  Book:
    type: object
    required:
      - id
      - title
      - author
      - links
    properties:
      id:
        description: "Unique book id"
        type: string
      title:
        description: "Name of the book"
        type: string
      author:
        description: "Author of the book"
        type: string
      synopsis:
        description: "Brief summary of the book"
        type: string
      links:
        type: object
        required:
          - self
          - reservations
          - reviews
        properties:
          self:
            type: string
          reservations:
            type: string
          reviews:
            type: string
