swagger: "2.0"
info:
  title: Books
  version: 1.1.0
paths:
  /books/{id}:
    get:
      summary: "Return book's details"
      description: "Returns book's details for given id"
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          description: "Unique book id"
          type: integer
          required: true
      responses:
        200:
          description: "Successfully returned a book"
          schema:
            $ref: "#/definitions/Book"
      deprecated: false
definitions:
  Book:
    type: object
    required:
      - id
      - title
      - author
      - links
    properties:
      id:
        description: "Unique book id"
        type: string
      title:
        description: "Name of the book"
        type: string
      author:
        description: "Author of the book"
        type: string
      synopsis:
        description: "Brief summary of the book"
        type: string
      links:
        type: object
        required:
          - self
          - reservations
          - reviews
        properties:
          self:
            type: string
          reservations:
            type: string
          reviews:
            type: string
